# Generated by Django 5.0.7 on 2024-07-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_friendrequestmodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FriendRequestModel",
            new_name="FriendRequest",
        ),
    ]
