# Generated by Django 5.0.7 on 2024-08-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_postmodel_likemodel_commentmodel_sharemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
