# Generated by Django 5.0.7 on 2024-08-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_postmodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="caption",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
