# Generated by Django 5.0.7 on 2024-08-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_postmodel_caption_alter_postmodel_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CommentModel",
            new_name="Comment",
        ),
        migrations.RenameModel(
            old_name="LikeModel",
            new_name="Like",
        ),
        migrations.RenameModel(
            old_name="PostModel",
            new_name="Post",
        ),
        migrations.RenameModel(
            old_name="ShareModel",
            new_name="Share",
        ),
    ]
